### ISSUE TITLE
Gradle?

### ISSUE THREAD

**Issue by athirukk** [malmstein/fenster#10]
Hi,

Do you have Gradle dependency set for this library? I am having issues in setting Maven... :(

Your library seems promising and I could not get a SO links discussing about this.

**Comment by athirukk** [comment]
Ok, I managed to add it as library in my project. Thats cool, but does this library support API 10 (Gingernread) by default?

Or the code needs to be tweaked to run for API Level 10? Please let me know.

**Comment by HarshEvilGeek** [comment]
I'm not the author, not have I contributed to this library, but I think I can answer this.

This library uses TextureView and features from it. It will not work with anything below API 14.

**Comment by malmstein** [comment]
@athirukk the library requires minSDK = 14. It has been finally published to jcenter today
