### ISSUE TITLE
Issue with gradle sync

### ISSUE THREAD

**Issue by tejaspawar1993** [malmstein/fenster#12]
https://oss.sonatype.org/content/repositories/snapshots/com/malmstein/ does not have fenster directory. 
While compiling it is trying to find fenster directory but it it not there. Hence giving following error:

Error:Could not find com.malmstein:fenster:0.1-SNAPSHOT.
Searched in the following locations:
    file:/home/pc-name/android-studio/gradle/m2repository/com/malmstein/fenster/0.1-SNAPSHOT/maven-metadata.xml
    file:/home/pc-name/android-studio/gradle/m2repository/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.pom
    file:/home/pc-name/android-studio/gradle/m2repository/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.jar
    https://repo1.maven.org/maven2/com/malmstein/fenster/0.1-SNAPSHOT/maven-metadata.xml
    https://repo1.maven.org/maven2/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.pom
    https://repo1.maven.org/maven2/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.jar
    https://oss.sonatype.org/content/repositories/snapshots/com/malmstein/fenster/0.1-SNAPSHOT/maven-metadata.xml
    https://oss.sonatype.org/content/repositories/snapshots/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.pom
    https://oss.sonatype.org/content/repositories/snapshots/com/malmstein/fenster/0.1-SNAPSHOT/fenster-0.1-SNAPSHOT.jar
Required by:
    pc-name2:app:unspecified

**Comment by Rensodiaz** [comment]
I'm having this issue too.

**Comment by malmstein** [comment]
Hi @tejaspawar1993 @Rensodiaz sorry about the inconvenience, the library is finally released to jcenter. The aar should be available shortly, check the README for further details.

**Comment by malmstein** [comment]
@tejaspawar1993 @Rensodiaz is this still happening?

**Comment by Rensodiaz** [comment]
No, is working as it should, :dancer:

**Comment by malmstein** [comment]
awesome, thanks @Rensodiaz !
