### ISSUE TITLE
MediaController and Brightness not Working

### ISSUE THREAD

**Issue by TheReprator** [malmstein/fenster#13]
I had tried to implement the media controller but other other than play/ pause button no other button like forward, backward media button is not working and also the brightness seekbar had no effect on screen.

**Comment by malmstein** [comment]
Hello @TheGreat0004, would you be able to provide me with the xml layout you are using? https://github.com/malmstein/fenster/blob/master/library/src/main/java/com/malmstein/fenster/controller/SimpleMediaFensterPlayerController.java is designed to do exactly what you are looking for

**Comment by TheReprator** [comment]
@malmstein , i am using your own default sample app Gesture media player and it is not working, the fragment xml is as follows,

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:tools="http://schemas.android.com/tools"
  android:layout_width="match_parent"
  android:layout_height="match_parent">

  <com.malmstein.fenster.view.FensterVideoView
    android:id="@+id/fen__play_video_texture"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:keepScreenOn="true"
    android:fitsSystemWindows="true" />

  <com.malmstein.fenster.controller.MediaFensterPlayerController
    android:id="@+id/fen__play_video_controller"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_alignParentBottom="true" />

  <com.malmstein.fenster.view.FensterLoadingView
    android:id="@+id/fen__play_video_loading"
    android:layout_width="match_parent"
    android:layout_height="match_parent" />

</RelativeLayout>
