### ISSUE TITLE
Remove your library ic_launcher icons

### ISSUE THREAD

**Issue by alirezaaa** [malmstein/fenster#15]
Hi,

Please remove `ic_launcher.png` icons from your library because it causes error on building when another library uses those icons on drawable folders. Or I think you can add those icons to mipmap folders. Thanks.

**Comment by benjaminbarbe** [comment]
+1

**Comment by commonsguy** [comment]
More accurately, remove all attributes from `<application>` in your manifest. Your library does not need them, and they cause integration problems for people trying to use the library.

The workaround is to add `tools:replace="android:icon,android:label,android:allowBackup"` to the `<application>` element of the manifest to replace the values coming from the library.

**Comment by malmstein** [comment]
:+1:

**Comment by malmstein** [comment]
Fixed https://github.com/malmstein/fenster/releases/tag/v.0.0.2
