### ISSUE TITLE
Thank you for Your great work and how can i cache the video play from a url?

### ISSUE THREAD

**Issue by LiuDeng** [malmstein/fenster#16]
Thank you for Your great work and how can i cache the video play from a url?
Best Wishes~

**Comment by malmstein** [comment]
Hello @LiuDeng, what do you mean by caching? 

If you are talking about changing the size of the buffer dedicated to the stream I'm afraid that's not possible. Fenster is not modifying any of the internal features of the `MediaPlayer`.
