### ISSUE TITLE
Add Support for Playing Videos from Assets

### ISSUE THREAD

**Issue by commonsguy** [malmstein/fenster#17]
It appears to be possible to teach `MediaPlayer` to play media from `assets/`, [using a `FileDescriptor` that you get from `openFd()` on `AssetManager`](http://stackoverflow.com/a/21955479/115145).

Ideally, `FensterVideoView` would either:

- Recognize `file:///android_asset/` `Uri` values, parse out the path portion, use that with `openFd()`, and pass that to `MediaPlayer`, or

- Support supplying a `FileDescriptor`, instead of a `Uri`, as the source of the video

Thanks!

**Comment by commonsguy** [comment]
For example, you could replace:

```
                mMediaPlayer.setDataSource(getContext(), mUri, mHeaders);
```

with something like:

```
            if ("file".equals(mUri.getScheme()) &&
              "android_asset".equals(mUri.getPathSegments().get(0))) {
                ArrayList<String> path=new ArrayList<String>(mUri.getPathSegments());

                path.remove(0); // get rid of the android_asset bit

                String assetPath=TextUtils.join("/", path);
                AssetFileDescriptor
                  afd=getContext().getAssets().openFd(assetPath);
                mMediaPlayer.setDataSource(afd.getFileDescriptor(),
                  afd.getStartOffset(), afd.getLength());
            }
            else {
                mMediaPlayer.setDataSource(getContext(), mUri,
                  mHeaders);
            }
```

in `FensterVideoView`, in the `openVideo()` method.

**Comment by malmstein** [comment]
I'm thinking about something like this, adding a new public API without modifying the internals too much:
```
if (localFile) {
     AssetFileDescriptor assetFileDescriptor = getResources().openRawResourceFd(R.raw.big_buck_bunny);
     textureView.setVideo(assetFileDescriptor);
} else {
    textureView.setVideo("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4");
}
```

What do you think @commonsguy?

**Comment by commonsguy** [comment]
@malmstein That would be wonderful from my standpoint. :-)

**Comment by malmstein** [comment]
Fixed https://github.com/malmstein/fenster/releases/tag/v.0.0.2
