### ISSUE TITLE
Galaxy Tab P3100(Android version 4.1.2) media controller is not visible

### ISSUE THREAD

**Issue by dibakarece** [malmstein/fenster#19]
I am not getting media controller visible in 4.1.2 devices as it's system UI visibility is not changed.Please help.It's urgent.Your video player is too good to handle with but please sort this issue out.

**Comment by malmstein** [comment]
Hello @dibakarece, would you be able to provide more data? It'd be helpful to see the xml layout you're using and the system UI visibility calls you're making in the Activity.

**Comment by dibakarece** [comment]
Thank u for your reply.I have handle this think from my own.
