### ISSUE TITLE
A TextureView or a subclass can only be used with hardware acceleration enabled.

### ISSUE THREAD

**Issue by rushabh13** [malmstein/fenster#2]
When i run your demo project, it will display this message on logcat and on the screen, nothing is displayed.......!

i have already set android:hardwareAccelerated="true" in manifest file....

what is issue then?

**Comment by iamnaran** [comment]
same isssue 👎  any solution ?

**Comment by malmstein** [comment]
@iamnaran I haven't updated this project in a while. I don't think I'll be doing it in the near future, but the beauty of OSS is that you could fork this project or even create a pull requests with the changes to fix it.
