### ISSUE TITLE
Add support for ScaledType

### ISSUE THREAD

**Issue by Aracem** [malmstein/fenster#5]
Add support for scaledType attribute to expand, crop ... the video.
For example, to play videos with different resolution than the VideoTextureview without the black bars

**Comment by Aracem** [comment]
API16+

mediaPlayer.setVideoScalingMode(MediaPlayer.VIDEO_SCALING_MODE_SCALE_TO_FIT_WITH_CROPPING);

**Comment by maxxx** [comment]
+1 for this

**Comment by malmstein** [comment]
Fixed https://github.com/malmstein/fenster/releases/tag/v.0.0.2

**Comment by Aracem** [comment]
Thanks @malmstein :clap: :dancer: :+1:
