### ISSUE TITLE
How to correctly use in a ListView or how to properly recyclye?

### ISSUE THREAD

**Issue by vijayrawatsan** [malmstein/fenster#8]
Hi,
When I try to recycle the FenesterView, a screen shot of previous video is shown any idea how can i clear the surfacetexture.

**Comment by malmstein** [comment]
Hi @vijayrawatsan, thanks for adding the issue.

May I ask why do you want to display a video in a ListView? Once the View is off the screen the adapter will recycle and it'd be a lot of effort to bring it back.

**Comment by osiloke** [comment]
i'm guessing something like facebook feed, but i think the use a gif and then you click through for an activity popup of the video

**Comment by malmstein** [comment]
It's not a very good idea to deal with `MediaPlayer` inside an `Adapter` that recycles `Views`.
